POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "user",
    "password": "pass"
}

###

GET http://localhost:3000/contacts/1

### 
GET http://localhost:3000/posts?_embed=comments
Authorization: Bearer 12dea96fec20593566ab75692c9949596833adc9
###
GET http://localhost:3000/comments?_embed=post&_token=12dea96fec20593566ab75692c9949596833adc9

###
GET http://localhost:3000/api/v1/contacts?_embed=groups

###

GET http://localhost:3000/contacts?_embed=phones

### 
GET http://localhost:3000/groups?_embed=contacts

###
GET http://localhost:3000/contacts?groupId=1



###
GET http://localhost:3000/comments?postId=1
###
GET http://localhost:3000/members?_embed=clubs

###
GET http://localhost:3000/clubs?_embed=members

###
DELETE http://localhost:3000/posts/1?_dependent=comments

### 
DELETE http://localhost:3000/contacts/2


### 
DELETE http://localhost:3000/clubs/1